import { strict as assert } from 'node:assert';
import { execFileSync, spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { after, before, test } from 'node:test';
import { fileURLToPath } from 'node:url';

const scriptPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'strip-agent-attribution.mjs',
);

let workDir;

before(() => {
  workDir = mkdtempSync(path.join(os.tmpdir(), 'strip-agent-attribution-'));
});

after(() => rmSync(workDir, { force: true, recursive: true }));

/** Runs the script as git's commit-msg hook would, on a message file. */
function stripMessage(message) {
  const file = path.join(workDir, 'COMMIT_EDITMSG');
  writeFileSync(file, message);
  const result = spawnSync(process.execPath, [scriptPath, file], { encoding: 'utf8' });
  return { ...result, message: readFileSync(file, 'utf8') };
}

// Real trailers from public commits: each agent credits itself with its own
// name and address, a human co-author uses the same trailer, and git reads the
// key in any letter case.
test('removes every co-author trailer, whatever the agent or letter case', () => {
  const result = stripMessage(
    [
      'feat: add a setting',
      '',
      'Body line one.',
      '',
      'Refs: #12',
      'Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>',
      'Co-authored-by: Codex <noreply@openai.com>',
      'co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>',
      'CO-AUTHORED-BY: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>',
      'Co-authored-by: Roo Code <roo@code.local>',
      'Co-authored-by: Jane Doe <jane@example.com>',
      '',
    ].join('\n'),
  );

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.message, 'feat: add a setting\n\nBody line one.\n\nRefs: #12\n');
  assert.match(result.stderr, /removed 6 /);
});

test('removes agent "Generated with" footers and session-link trailers', () => {
  const result = stripMessage(
    [
      'fix: handle empty input',
      '',
      'Explain the change.',
      '',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      '💘 Generated with Crush',
      'Generated with Claude Code',
      '🤖 Generated with [opencode](https://opencode.ai)',
      '',
      'Claude-Session: https://claude.ai/code/session_01MgGDWYuyaroMrgLB5derfq',
      'Amp-Thread-ID: https://ampcode.com/threads/T-01a0a44d-b3d8-706a-9f0e-bece137e98a9',
      '',
    ].join('\n'),
  );

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.message, 'fix: handle empty input\n\nExplain the change.\n');
});

test('recognizes attribution in a message saved with Windows line endings', () => {
  const result = stripMessage(
    'fix: handle empty input\r\n\r\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\r\n\r\nCo-authored-by: Codex <noreply@openai.com>\r\n',
  );

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.message, 'fix: handle empty input\n');
});

test('leaves a message without attribution byte-for-byte unchanged', () => {
  const message = [
    'docs: explain the build',
    '',
    'Generated by `pnpm run build` from src/.',
    '- Generated with esbuild, then minified.',
    'Co-author credit for the idea goes to the reviewers.',
    '',
    '',
    'Refs: #12',
    'Signed-off-by: Jane Doe <jane@example.com>',
    '',
  ].join('\n');

  const result = stripMessage(message);

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.message, message);
  assert.equal(result.stderr, '');
});

test('keeps the verbose-commit diff below the scissors line untouched', () => {
  const diff = [
    '# ------------------------ >8 ------------------------',
    '# Do not modify or remove the line above.',
    '# Everything below it will be ignored.',
    'diff --git a/notes.txt b/notes.txt',
    '+Co-authored-by: Codex <noreply@openai.com>',
    '',
  ].join('\n');

  const result = stripMessage(
    `feat: add notes\n\nCo-authored-by: Codex <noreply@openai.com>\n${diff}`,
  );

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.message, `feat: add notes\n${diff}`);
});

test('git records the cleaned message when the script runs as the commit-msg hook', () => {
  const repo = path.join(workDir, 'repo');
  const hooks = path.join(workDir, 'hooks');
  mkdirSync(hooks, { recursive: true });
  const hook = path.join(hooks, 'commit-msg');
  writeFileSync(hook, `#!/bin/sh\nexec node "${scriptPath.replaceAll('\\', '/')}" "$1"\n`);
  chmodSync(hook, 0o755);

  const git = (...args) =>
    execFileSync(
      'git',
      [
        '-c',
        'user.name=Test',
        '-c',
        'user.email=test@example.com',
        '-c',
        'commit.gpgsign=false',
        '-c',
        `core.hooksPath=${hooks}`,
        ...args,
      ],
      { cwd: repo, encoding: 'utf8' },
    );
  mkdirSync(repo);
  git('init', '-q');
  git(
    'commit',
    '-q',
    '--allow-empty',
    '-m',
    'chore: tidy up',
    '-m',
    'Co-Authored-By: Claude <noreply@anthropic.com>',
  );

  assert.equal(git('log', '-1', '--format=%B').trim(), 'chore: tidy up');
});

test('fails without a message file, so a broken hook setup cannot pass silently', () => {
  const result = spawnSync(process.execPath, [scriptPath], { encoding: 'utf8' });

  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /usage/i);
});
